# Standardization VS Normalization by `Mr. Harshit Dawar! `
* For Deep understanding of this topic, check out this [blog](https://harshitdawar.medium.com/difference-between-standardization-normalization-99be0320c1b1).

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [44]:
data = np.random.randint(1, 100, size = (10, 10))

In [45]:
data

array([[41, 37, 97, 82, 70, 80, 12, 90, 36, 30],
       [92, 37, 53,  3, 66, 30, 29,  8, 57, 83],
       [88, 81, 82, 79, 86, 92, 27, 11, 91,  2],
       [66, 28, 69, 37, 15, 77, 39, 62, 60, 91],
       [17, 93, 13, 65,  6,  2, 30, 39, 81, 73],
       [88, 76, 73,  3, 66, 38, 12, 40, 59, 18],
       [59, 17, 93, 33, 68, 95, 72, 27, 78, 50],
       [58, 69, 32, 62, 86, 56, 52, 59, 13, 98],
       [ 1, 20, 86, 69, 53, 95, 44, 32, 92, 45],
       [20, 53, 78, 66, 47, 29, 43, 73, 42, 95]])

## Standardized Data

In [46]:
scaledData = StandardScaler().fit_transform(data)

In [47]:
scaledData

array([[-0.39069091, -0.54657322,  1.13953488,  1.15478833,  0.53286421,
         0.65522742, -1.38749187,  1.81935267, -1.02853054, -0.87296497],
       [ 1.26974547, -0.54657322, -0.56589147, -1.6872141 ,  0.37728342,
        -0.9351304 , -0.40468513, -1.430907  , -0.16109514,  0.75044357],
       [ 1.13951516,  1.15904533,  0.55813953,  1.04686419,  1.15518738,
         1.0369133 , -0.52030945, -1.31199506,  1.24332407, -1.73061476],
       [ 0.42324849, -0.89544974,  0.05426357, -0.46407382, -1.60637167,
         0.55980595,  0.17343648,  0.70950791, -0.0371758 ,  0.99548637],
       [-1.17207274,  1.62421402, -2.11627907,  0.54321819, -1.95642845,
        -1.82573078, -0.34687297, -0.2021503 ,  0.83025959,  0.44414007],
       [ 1.13951516,  0.96522504,  0.20930233, -1.6872141 ,  0.37728342,
        -0.68067315, -1.38749187, -0.16251298, -0.07848225, -1.24052916],
       [ 0.19534546, -1.32185437,  0.98449612, -0.60797267,  0.45507382,
         1.13233477,  2.08123781, -0.67779805

## Normalized Data

In [48]:
scaledData = MinMaxScaler().fit_transform(data)

In [49]:
scaledData

array([[0.43956044, 0.26315789, 1.        , 1.        , 0.8       ,
        0.83870968, 0.        , 1.        , 0.29113924, 0.29166667],
       [1.        , 0.26315789, 0.47619048, 0.        , 0.75      ,
        0.30107527, 0.28333333, 0.        , 0.55696203, 0.84375   ],
       [0.95604396, 0.84210526, 0.82142857, 0.96202532, 1.        ,
        0.96774194, 0.25      , 0.03658537, 0.98734177, 0.        ],
       [0.71428571, 0.14473684, 0.66666667, 0.43037975, 0.1125    ,
        0.80645161, 0.45      , 0.65853659, 0.59493671, 0.92708333],
       [0.17582418, 1.        , 0.        , 0.78481013, 0.        ,
        0.        , 0.3       , 0.37804878, 0.86075949, 0.73958333],
       [0.95604396, 0.77631579, 0.71428571, 0.        , 0.75      ,
        0.38709677, 0.        , 0.3902439 , 0.58227848, 0.16666667],
       [0.63736264, 0.        , 0.95238095, 0.37974684, 0.775     ,
        1.        , 1.        , 0.23170732, 0.82278481, 0.5       ],
       [0.62637363, 0.68421053, 0.2261904