# Synthetic Recurrent Neural Networks (RNN) using Basic Python Packages with comparison of the Actual API RNN

## Importing the required Libraries

In [1]:
from tensorflow.keras.layers import SimpleRNN, Dense, Input, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt

In [5]:
Number_Of_Samples = 100
Dimensions = 3
Hidden_Units = 5
Sequqnce_Length = 15
Outputs = 5

data = np.random.randn(Number_Of_Samples, Sequqnce_Length, Dimensions)

In [8]:
data.shape

(100, 15, 3)

## Constructing a RNN from API

In [9]:
inputShape = Input(shape = (Sequqnce_Length, Dimensions))
RNNModel_From_API = SimpleRNN(Hidden_Units)(inputShape)
RNNModel_From_API = Dense(Outputs)(RNNModel_From_API)

RNNModel_From_API = Model(inputShape, RNNModel_From_API)

In [10]:
RNNModel_From_API.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 15, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 5)                 30        
Total params: 75
Trainable params: 75
Non-trainable params: 0
_________________________________________________________________


In [14]:
RNNModel_From_API.predict(data)[0]

array([ 0.06354403,  0.02781903, -0.25603473,  0.5296577 , -0.5586113 ],
      dtype=float32)

### Checking SimpleRNN Layer aprameters & their Shapes

In [19]:
RNNModel_From_API.layers[1].get_weights()

[array([[ 0.5278395 ,  0.33901566,  0.72987264, -0.04462039, -0.37976032],
        [-0.31247956, -0.4856124 ,  0.607722  ,  0.65782124,  0.7901283 ],
        [-0.3619125 , -0.37909445, -0.3027045 ,  0.13091171,  0.60899395]],
       dtype=float32),
 array([[ 0.21730196,  0.4180219 ,  0.13075541,  0.280215  ,  0.8260872 ],
        [-0.02677928,  0.3702965 , -0.79860145, -0.46239284,  0.10291667],
        [ 0.7960546 , -0.5351484 , -0.26362926,  0.00335152,  0.10198843],
        [-0.5478907 , -0.6336522 , -0.1699108 , -0.06771715,  0.5146313 ],
        [-0.13481686,  0.01546921, -0.49675804,  0.83849597, -0.17816022]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
p, q, r = RNNModel_From_API.layers[1].get_weights()
