# Synthetic Recurrent Neural Networks (RNN) using Basic Python Packages with comparison of the Actual API RNN

## Importing the required Libraries

In [1]:
from tensorflow.keras.layers import SimpleRNN, Dense, Input, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt

In [65]:
Number_Of_Samples = 100
Dimensions = 3
Hidden_Units = 5
Sequqnce_Length = 15
Outputs = 5

data = np.random.randn(Number_Of_Samples, Sequqnce_Length, Dimensions)

In [66]:
data.shape

(100, 15, 3)

## Constructing a RNN from API

In [67]:
inputShape = Input(shape = (Sequqnce_Length, Dimensions))
RNNModel_From_API = SimpleRNN(Hidden_Units)(inputShape)
RNNModel_From_API = Dense(Outputs)(RNNModel_From_API)

RNNModel_From_API = Model(inputShape, RNNModel_From_API)

In [68]:
RNNModel_From_API.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 15, 3)]           0         
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 30        
Total params: 75
Trainable params: 75
Non-trainable params: 0
_________________________________________________________________


In [69]:
data[0].shape

(15, 3)

In [70]:
RNNModel_From_API.predict(data)[0]

array([ 0.71518403, -0.4893237 , -0.9059198 ,  0.82166475, -0.5105824 ],
      dtype=float32)

### Checking SimpleRNN Layer aprameters & their Shapes

In [71]:
## Layers in the Model
RNNModel_From_API.layers

In [72]:
RNNModel_From_API.layers[1].get_weights()

[array([[ 0.72209054, -0.81780547, -0.4364722 ,  0.20916647,  0.820213  ],
        [ 0.86559814,  0.44415253,  0.02617997,  0.32367736,  0.1384502 ],
        [ 0.77787536, -0.6454112 , -0.19293809,  0.21988755,  0.776653  ]],
       dtype=float32),
 array([[ 7.0458293e-02, -7.7380264e-01, -4.0028641e-01, -4.0357441e-01,
         -2.7048758e-01],
        [ 6.5845001e-04, -2.9930481e-01, -2.0159107e-01,  9.1019279e-01,
         -2.0328900e-01],
        [ 5.8308470e-01, -3.5972294e-01,  2.5072199e-01,  8.8292390e-02,
          6.7819947e-01],
        [-7.1349287e-01, -1.5837801e-01, -2.7081540e-01,  2.8239995e-02,
          6.2586403e-01],
        [-3.8206699e-01, -3.9643663e-01,  8.1420469e-01,  9.1529042e-03,
         -1.8398291e-01]], dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [73]:
p, q, r = RNNModel_From_API.layers[1].get_weights()
print("Shape of Weights of Input for Hidden Layer {} \nShape of Weights of Hidden Parameters for Hidden Layers {}\nShape of the Biases for the Hidden Layer {}".format(
    p.shape, q.shape, r.shape))

Shape of Weights of Input for Hidden Layer (3, 5) 
Shape of Weights of Hidden Parameters for Hidden Layers (5, 5)
Shape of the Biases for the Hidden Layer (5,)


In [74]:
RNNModel_From_API.layers[2].get_weights()

[array([[ 0.68569887, -0.5480356 , -0.2710864 ,  0.30896258,  0.34104073],
        [-0.1989544 , -0.05351752, -0.19102192,  0.25469458, -0.35059613],
        [-0.23485994,  0.3490299 ,  0.63393176,  0.7743679 , -0.27296478],
        [ 0.36506128,  0.0164336 , -0.6726582 ,  0.49134922, -0.5645117 ],
        [ 0.10606974, -0.08883727, -0.73820823,  0.28067505,  0.61149573]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [75]:
a, b = RNNModel_From_API.layers[2].get_weights()
print("Shape of Weights for the output Layer {} \nShape of Biases for the Output Layer {}".format(a.shape, b.shape))

Shape of Weights for the output Layer (5, 5) 
Shape of Biases for the Output Layer (5,)


In [76]:
data[0].shape

(15, 3)

## Creating Synthetic RNN

***Wx = Wieghts of the Input in Hidden Layer***

***Wh = Weights of the Hidden Parameters in the Hidden Layer***

***Bh = Biases of the Hidden Parameters in the Hidden Layer***

***Wo = Weights of the Output Parameters in the Output Layer***

***Bo = Biases of the Output Parameters in the Output Layer***

### Retrieving the required Wieghts

In [77]:
Wx, Wh, Bh = RNNModel_From_API.layers[1].get_weights()
Wo, Bo = RNNModel_From_API.layers[2].get_weights()


In [82]:
sampleData = data[0]
hiddenState = np.zeros(Hidden_Units)
output = []

for sequence in range(Sequqnce_Length):
    hiddenParameter = np.tanh( sampleData[sequence].dot(Wx) + hiddenState.dot(Wh) + Bh )
    y = hiddenParameter.dot(Wo) + Bo
    
    output.append(y)
    hiddenState = hiddenParameter

print(output[-1])

[ 0.71518384 -0.48932357 -0.90591966  0.8216648  -0.51058244]


In [80]:
print(RNNModel_From_API.predict(data)[0])

[ 0.71518403 -0.4893237  -0.9059198   0.82166475 -0.5105824 ]
